### ISSUE TITLE
cpu_adam cuda is missing or is incompatible with installed torch, only cpu ops can be compiled!

### ISSUE THREAD

**Issue by susht3** [deepspeedai/DeepSpeed#4355]
i can train on cpu, but get error when train with deepspeed,
i got the warning and errors as following:

[WARNING]  cpu_adam cuda is missing or is incompatible with installed torch, only cpu ops can be compiled!
Using /home/sushuting/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...

Traceback (most recent call last):
  File "/nvme/nvme0//anaconda3/envs/py3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nvme/nvme0//anaconda3/envs/py3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/nvme/nvme0//github/clip/examples/AltCLIP/altclip_finetuning.py", line 67, in <module>
    trainer.train(model=model, train_dataset=dataset, collate_fn=cifar10_collate_fn)
  File "/nvme/nvme0//github/clip/flagai/trainer.py", line 566, in train
    lm_loss, _ = self.train_step_pytorch(
  File "/nvme/nvme0//github/clip/flagai/trainer.py", line 705, in train_step_pytorch
    optimizer.step()
  File "/nvme/nvme0//anaconda3/envs/py3/lib/python3.8/site-packages/torch/optim/optimizer.py", line 280, in wrapper      
    out = func(*args, **kwargs)
  File "/nvme/nvme0//anaconda3/envs/py3/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_co
ntext
    return func(*args, **kwargs)
  File "/nvme/nvme0//anaconda3/envs/py3/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 150, in step   
    assert p.device == device, f"CPUAdam param is on {p.device} and must be 'cpu', make " \
AssertionError: CPUAdam param is on cuda:0 and must be 'cpu', make sure you enabled 'offload_optimizer': 'cpu' in your ZeRO config
.

**Comment by mrwyattii** [comment]
@susht3 can you please provide a reproducer for this error?

Share the output of `ds_report` as well. Thank you

**Comment by kiddyboots216** [comment]
> @susht3 can you please provide a reproducer for this error?
> 
> Share the output of `ds_report` as well. Thank you

I had a similar issue, described here https://github.com/microsoft/DeepSpeed/issues/3613#issuecomment-1726016406

**Comment by loadams** [comment]
@kiddyboots216 - just adding here, the issue was resolved by increasing the total memory, however the original issue would be best resolved by seeing the ds_report and ds_config.

**Comment by sfc-gh-truwase** [comment]
Closing as it seems resolved.
