### ISSUE TITLE
[BUG]RuntimeError: disagreement between rank0 and rank1: rank0:

### ISSUE THREAD

**Issue by yiyepiaoling0715** [deepspeedai/DeepSpeed#5799]
**Describe the bug**
`2024-07-24 08:45:13.616
Traceback (most recent call last):
2024-07-24 08:45:13.616
  File "/mft_peft_hf/src/pefts/mft_accelerate.py", line 506, in <module>
2024-07-24 08:45:13.616
    main()
2024-07-24 08:45:13.616
  File "/mft_peft_hf/src/pefts/mft_accelerate.py", line 502, in main
2024-07-24 08:45:13.616
    accelerate_train(accelerator, model, train_dataloader, valid_dataloader, optimizer, lr_scheduler, num_update_steps_per_epoch, len(train_dataset), args)
2024-07-24 08:45:13.616
  File "/mft_peft_hf/src/pefts/train_utils.py", line 454, in accelerate_train
2024-07-24 08:45:13.616
    stall_num_iter=eval_and_save_model(model=model,valid_dataloader=valid_dataloader,
2024-07-24 08:45:13.616
  File "/mft_peft_hf/src/pefts/train_utils.py", line 177, in eval_and_save_model
2024-07-24 08:45:13.616
    outputs = model(
2024-07-24 08:45:13.616
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
2024-07-24 08:45:13.616
    return self._call_impl(*args, **kwargs)
2024-07-24 08:45:13.616
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
2024-07-24 08:45:13.617
    return forward_call(*args, **kwargs)
2024-07-24 08:45:13.617
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
2024-07-24 08:45:13.617
    ret_val = func(*args, **kwargs)
2024-07-24 08:45:13.617
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1852, in forward
2024-07-24 08:45:13.617
    loss = self.module(*inputs, **kwargs)
2024-07-24 08:45:13.617
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
2024-07-24 08:45:13.617
    return self._call_impl(*args, **kwargs)
2024-07-24 08:45:13.617
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1574, in _call_impl
2024-07-24 08:45:13.617
    hook_result = hook(self, args, result)
2024-07-24 08:45:13.617
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
2024-07-24 08:45:13.617
    ret_val = func(*args, **kwargs)
2024-07-24 08:45:13.617
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 232, in _end_of_forward_hook
2024-07-24 08:45:13.617
    self.get_param_coordinator(training=False).reset_step()
2024-07-24 08:45:13.617
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 212, in reset_step
2024-07-24 08:45:13.617
    assert_ints_same_as_other_ranks([m.id for m in self.__submodule_order])
2024-07-24 08:45:13.617
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
2024-07-24 08:45:13.617
    ret_val = func(*args, **kwargs)
2024-07-24 08:45:13.617
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/zero/utils.py", line 88, in assert_ints_same_as_other_ranks
2024-07-24 08:45:13.617
    raise RuntimeError(f"disagreement between rank0 and rank{dist.get_rank()}: "
2024-07-24 08:45:13.618
RuntimeError: disagreement between rank0 and rank1: rank0: [-4856502234927317838, -4837927448405689103, -4817095843398730680, 4367010062678113154, -4969514249078490040, -4869731286091744011, 4430623072410221714, -4883945862632358737, 4370247986990365646, -4929826814247486204, -4883523854155367210, 4315358989988543511, 4338722199025073538, -4856644325325882266, -4819630533390615224, 4419645702939655429, 4380661543225310345, 4424007278692514572, 4297765751676648743, -4860162043132855204, -4826384794659865655, -4845665862791480413, 4256952728304991527, 4385869128786263371, 4313950541365656732, -4861568679267713931, 4362929409957706367, 4381787964973071354, 4353921536386743255, 4409091046283426808, 4411904629965765530, -4842006037403911034, 4358143216528407511, -4939818836612989834, 4421895417540328718, -4905197328590259189, -4940381900382716724, -4827652069858624380, 4381505596634905524, 4227820819850149000, 4353640003424992572, 4352372588632390774, 4221346543172697420, 4350121072299588773, 4396283881147546902, -4857488398068958207, -4796126720021349271, -4884087042472133705, -4858754266665894527, -4957129807543780457, 4309588134500743823, -4856643133475210470, 4310855693149223808, 4364195860508490957, 4358706501468142979, 4377846933044149391, 4374328613940968601, -4842991330811921060, -4888449232480486182, -4813014011738800816, -4894082092802098007, -4840598428439987048, 4402476502420765903, 4310855899285470310, -4802036204171346774, -4812732798738318750, 4342381640011529445, -4853968734644126681, 4323803986580651212, -4909560437673772368, 4360956512418315203, -4794859296643564545, 4403602082391800739, 4415704844942261267, -4837081243220984477, -4920960912985277136, 4393468948860287906, 4262442933474999249, -4864946756979704780, 4382913946471087474, 4297204652854328351, 4353921355990580371, 4376580974243953333, 4283693478113492246, -4911674439920141159, 4264131444032813791, -4889717130420339579, -4823991211539252099, 4363210116147526773, 4372077733245107285, -4875221351676854986, 4156745151967214718, -4907730575452095343, 4372780692692777939, -4893375450437927865, 4315217634008972291, -4958256940102239048, -4926167583749161908, 4389809525014347126, 4406980054843374623, 4300721515959434234, -4842006095403860761, -4795564820155744940, -4853688384948880900, 4356736004848073926, -4856784553847243900, 4409509696079412355, -4893096028438905712, 4374188039667694259, 4273278949125536970, 4334781772692470814, 4352232553390325017, 4395861660117122215, -4924760067113993575, -4840598645334917886, -4966277606843532 ...
rank1: [0, 1, 2, 4, 17, 5, 6, 7, 8, 9, 11, 10, 18, 12, 13, 16, 14, 15, 19, 355, 20, 21, 22, 23, 24, 26, 25, 356, 27, 349, 29, 30, 33, 31, 32, 34, 35, 38, 36, 37, 39, 40, 43, 41, 42, 44, 45, 48, 46, 47, 49, 50, 53, 51, 52, 54, 55, 58, 56, 57, 59, 60, 63, 61, 62, 64, 65, 68, 66, 67, 69, 70, 73, 71, 72, 74, 75, 78, 76, 77, 79, 80, 83, 81, 82, 84, 85, 88, 86, 87, 89, 90, 93, 91, 92, 94, 95, 98, 96, 97, 99, 100, 103, 101, 102, 104, 105, 108, 106, 107, 109, 110, 113, 111, 112, 114, 115, 118, 116, 117, 119, 120, 123, 121, 122, 124, 125, 128, 126, 127, 129, 130, 133, 131, 132, 134, 135, 138, 136, 137, 139, 140, 143, 141, 142, 144, 145, 148, 146, 147, 149, 150, 153, 151, 152, 154, 155, 158, 156, 157, 159, 160, 163, 161, 162, 164, 165, 168, 166, 167, 169, 170, 173, 171, 172, 174, 175, 178, 176, 177, 179, 180, 183, 181, 182, 184, 185, 188, 186, 187, 189, 190, 193, 191, 192, 194, 195, 198, 196, 197, 204, 205, 208, 206, 207, 214, 215, 218, 216, 217, 219, 220, 223, 221, 222, 224, 225, 228, 226, 227, 229, 230, 233, 231, 232, 234, 235, 238, 236, 237, 239, 240, 243, 241, 242, 244, 245, 248, 246, 247, 249, 250, 253, 251, 252, 254, 255, 258, 256, 257, 259, 260, 263, 261, 262, 264, 265, 268, 266, 267, 269, 270, 273, 271, 272, 274, 275, 278, 276, 277, 279, 280, 283, 281, 282, 284, 285, 288, 286, 287, 289, 290, 293, 291, 292, 294, 295, 298, 296, 297, 299, 300, 303, 301, 302, 304, 305, 308, 306, 307, 309, 310, 313, 311, 312, 314, 315, 318, 316, 317, 324, 325, 328, 326, 327, 329, 330, 333, 331, 332, 334, 335, 338, 336, 337, 339, 340, 343, 341, 342, 344, 345, 348, 346, 347, 350, 351, 354, 352, 353, 357, 693, 358, 359, 360, 361, 362, 364, 363, 694, 365, 687, 367, 368, 371, 369, 370, 372, 373, 376, 374, 375, 377, 378, 381, 379, 380, 382, 383, 386, 384, 385, 387, 388, 391, 389, 390, 392, 393, 396, 394, 395, 402, 403, 406, 404, 405, 407, 408, 411, 409, 410, 412, 413, 416, 414, 415, 417, 418, 421, 419, 420, 422, 423, 426, 424, 425, 427, 428, 431, 429, 430, 432, 433, 436, 434, 435, 437, 438, 441, 439, 440, 442, 443, 446, 444, 445, 447, 448, 451, 449, 450, 452, 453, 456, 454, 455, 457, 458, 461, 459, 460, 462, 463, 466, 464, 465, 467, 468, 471, 469, 470, 472, 473, 476, 474, 4`
**To Reproduce**

**Expected behavior**

**ds_report output**
Please run `ds_report` to give us details about your setup.
`[WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.2
 [WARNING]  using untested triton version (2.2.0), only 1.0.0 is known to be compatible
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_lion ............... [NO] ....... [OKAY]
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
evoformer_attn ......... [NO] ....... [NO]
fp_quantizer ........... [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
fused_lion ............. [NO] ....... [OKAY]
inference_core_ops ..... [NO] ....... [OKAY]
cutlass_ops ............ [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
ragged_device_ops ...... [NO] ....... [OKAY]
ragged_ops ............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.2
 [WARNING]  using untested triton version (2.2.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/opt/conda/lib/python3.10/site-packages/torch']
torch version .................... 2.2.1
deepspeed install path ........... ['/home/jovyan/.local/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.14.4, unknown, unknown
torch cuda version ............... 12.1
torch hip version ................ None
nvcc version ..................... 12.1
deepspeed wheel compiled w. ...... torch 2.2, cuda 12.1
shared memory (/dev/shm) size .... 600.00 GB
`
**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version
 - Any other relevant info about your setup
``Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1082, in launch_command
    deepspeed_launcher(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 786, in deepspeed_launcher
    distrib_run.run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?
 accelerate launch --config_file  accelerate_ds3_config.yaml \
                /mft_peft_hf/src/pefts/mft_accelerate.py \
                --train_config  /mft_peft_hf/src/pefts/configs/llama_train_config.json 
**Docker context**
Are you using a specific docker image that you can share?
`absl-py                       2.1.0
accelerate                    0.32.1
aiohttp                       3.8.6
aiosignal                     1.3.1
annotated-types               0.7.0
anyio                         3.7.1
APScheduler                   3.10.4
archspec                      0.2.1
argon2-cffi                   23.1.0
argon2-cffi-bindings          21.2.0
asttokens                     2.0.5
astunparse                    1.6.3
async-timeout                 4.0.3
attrs                         23.1.0
autoawq                       0.2.5
autoawq_kernels               0.0.6
Babel                         2.15.0
bce-python-sdk                0.8.99
beautifulsoup4                4.12.2
bigcode-eval                  0.0.0
bitsandbytes                  0.43.1
bleach                        6.1.0
boltons                       23.0.0
boto3                         1.33.13
botocore                      1.33.13
Brotli                        1.0.9
certifi                       2024.2.2
cffi                          1.16.0
chardet                       4.0.0
charset-normalizer            2.0.4
click                         8.1.7
cloudpickle                   3.0.0
cmake                         3.30.0
cn2an                         0.5.22
colorama                      0.4.6
comm                          0.2.2
conda                         23.9.0
conda-build                   24.1.2
conda-content-trust           0.2.0
conda_index                   0.4.0
conda-libmamba-solver         23.7.0
conda-package-handling        2.2.0
conda_package_streaming       0.9.0
cryptography                  42.0.2
ctranslate2                   3.20.0
datasets                      2.20.0
debugpy                       1.8.2
decorator                     5.1.1
deepspeed                     0.14.4
defusedxml                    0.7.1
Deprecated                    1.2.14
detect-secrets                1.5.0
dill                          0.3.8
diskcache                     5.6.3
distro                        1.8.0
dnspython                     2.6.1
docker-pycreds                0.4.0
docopt                        0.6.2
docstring_parser              0.16
einops                        0.8.0
email_validator               2.2.0
et-xmlfile                    1.1.0
evaluate                      0.4.2
exceptiongroup                1.2.0
executing                     0.8.3
expecttest                    0.2.1
fastapi                       0.111.0
fastapi-cli                   0.0.4
fastjsonschema                2.20.0
filelock                      3.13.1
flash-attn                    2.6.0.post1
frozenlist                    1.4.1
fsspec                        2023.9.2
ftfy                          6.2.0
future                        1.0.0
fuzzywuzzy                    0.18.0
gibberish-detector            0.1.1
gitdb                         4.0.11
GitPython                     3.1.43
gmpy2                         2.1.2
greenlet                      3.0.3
grpcio                        1.64.1
h11                           0.14.0
hjson                         3.1.0
httpcore                      1.0.5
httptools                     0.6.1
httpx                         0.27.0
huggingface-hub               0.23.4
humanfriendly                 10.0
hypothesis                    6.98.10
idaas-sdk                     0.4.2
idna                          3.4
iniconfig                     2.0.0
interegular                   0.3.3
ipykernel                     6.29.5
ipython                       8.20.0
ipython-genutils              0.2.0
jedi                          0.18.1
Jinja2                        3.1.3
jmespath                      1.0.1
joblib                        1.4.2
json5                         0.9.25
jsonlines                     4.0.0
jsonpatch                     1.32
jsonpointer                   2.1
jsonschema                    4.19.2
jsonschema-specifications     2023.7.1
jupyter_client                8.6.2
jupyter_core                  5.7.2
jupyter-server                1.23.3
jupyterlab                    3.3.2
jupyterlab_pygments           0.3.0
jupyterlab_server             2.27.2
jwcrypto                      1.5.6
lark                          1.1.9
libarchive-c                  2.9
libmambapy                    1.5.3
lit                           18.1.8
llvmlite                      0.43.0
lm-format-enforcer            0.9.8
loguru                        0.7.2
lpai                          0.61.0
lpai-asset                    0.1.33
lxml                          5.2.2
Markdown                      3.6
markdown-it-py                3.0.0
MarkupSafe                    2.1.3
matplotlib-inline             0.1.6
mdurl                         0.1.2
menuinst                      2.0.2
minio                         7.2.7
mistune                       3.0.2
mkl-fft                       1.3.8
mkl-random                    1.2.4
mkl-service                   2.4.0
more-itertools                10.1.0
mosestokenizer                1.0.0
mpmath                        1.3.0
msgpack                       1.0.8
multidict                     6.0.5
multiprocess                  0.70.16
nbclassic                     0.5.6
nbclient                      0.10.0
nbconvert                     7.16.4
nbformat                      5.10.4
nest-asyncio                  1.6.0
networkx                      3.1
nibabel                       5.2.1
ninja                         1.11.1.1
nltk                          3.8.1
notebook_shim                 0.2.4
numba                         0.60.0
numpy                         1.26.3
numpyencoder                  0.3.0
nvidia-ml-py                  12.555.43
openai                        1.35.13
openfile                      0.0.7
openpyxl                      3.1.5
optree                        0.10.0
orjson                        3.10.6
outlines                      0.0.34
packaging                     23.1
pandas                        2.2.2
pandocfilters                 1.5.1
parso                         0.8.3
peft                          0.11.1
pexpect                       4.8.0
pillow                        10.2.0
pip                           23.3.1
pkginfo                       1.9.6
platformdirs                  3.10.0
pluggy                        1.5.0
portalocker                   2.10.0
proces                        0.1.7
progress                      1.6
prometheus_client             0.20.0
prompt-toolkit                3.0.43
protobuf                      4.25.3
protocol                      0.37
psutil                        5.9.0
ptyprocess                    0.7.0
pure-eval                     0.2.2
py-cpuinfo                    9.0.0
pyarrow                       16.1.0
pyarrow-hotfix                0.6
pybind11                      2.13.1
pycosat                       0.6.6
pycparser                     2.21
pycryptodome                  3.20.0
pydantic                      2.8.2
pydantic_core                 2.20.1
pydicom                       2.4.4
pyext                         0.7
Pygments                      2.15.1
pynvml                        11.5.0
pyOpenSSL                     24.0.0
pypng                         0.20220715.0
PySocks                       1.7.1
pytest                        8.2.2
python-box                    7.2.0
python-dateutil               2.8.2
python-dotenv                 1.0.1
python-etcd                   0.4.5
python-multipart              0.0.9
pytz                          2023.3.post1
PyYAML                        6.0.1
pyzmq                         26.0.3
qrcode                        7.4.2
rank-bm25                     0.2.2
ray                           2.32.0
rclone-python-lp-asset        0.1.13
referencing                   0.30.2
regex                         2024.5.15
requests                      2.31.0
rich                          13.7.1
rpds-py                       0.10.6
ruamel.yaml                   0.17.21
ruamel.yaml.clib              0.2.6
s3transfer                    0.8.2
sacrebleu                     2.4.2
safetensors                   0.4.3
scikit-learn                  1.5.1
scipy                         1.14.0
Send2Trash                    1.8.3
sentence-transformers         3.0.1
sentencepiece                 0.2.0
sentry-sdk                    2.9.0
setproctitle                  1.3.3
setuptools                    67.7.2
shellingham                   1.5.4
shtab                         1.7.1
six                           1.16.0
smmap                         5.0.1
sniffio                       1.3.1
sortedcontainers              2.4.0
soupsieve                     2.5
SQLAlchemy                    2.0.31
stack-data                    0.2.0
starlette                     0.37.2
sympy                         1.12
tabulate                      0.9.0
tblib                         3.0.0
tensorboard                   2.17.0
tensorboard-data-server       0.7.2
terminado                     0.18.1
threadpoolctl                 3.5.0
tiktoken                      0.6.0
timeout-decorator             0.5.0
tinycss2                      1.3.0
tokenizers                    0.19.1
tomli                         2.0.1
toolwrapper                   2.1.0
toolz                         0.12.0
torch                         2.2.1
torchaudio                    2.2.1
torchelastic                  0.2.2
torchvision                   0.17.1
tornado                       6.4.1
tqdm                          4.66.4
traitlets                     5.7.1
transformers                  4.43.1
transformers-stream-generator 0.0.5
tree-sitter                   0.21.3
triton                        2.2.0
trl                           0.9.6
truststore                    0.8.0
typer                         0.12.3
types-dataclasses             0.6.6
typing_extensions             4.12.2
tyro                          0.8.5
tzdata                        2024.1
tzlocal                       5.2
ujson                         5.10.0
urllib3                       2.0.7
utils                         1.0.2
uvicorn                       0.30.1
uvloop                        0.19.0
vllm                          0.4.1
vllm-nccl-cu12                2.18.1.0.4.0
wandb                         0.17.4
watchfiles                    0.22.0
wcwidth                       0.2.13
webencodings                  0.5.1
websocket-client              1.8.0
websockets                    12.0
Werkzeug                      3.0.3
wheel                         0.41.2
wrapt                         1.16.0
xformers                      0.0.25
xorbits                       0.7.2
xoscar                        0.3.2
xxhash                        3.4.1
yarl                          1.9.4
zstandard                     0.19.0`
**Additional context**
`compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  offload_optimizer_device: cpu
  offload_param_device: cpu
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
machine_rank: 0
main_training_function: main
megatron_lm_config: {}
# mixed_precision: 'bf16'
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
use_cpu: true
mixed_precision: bf16`

**Comment by eonsparks** [comment]
### **Error Description:**
The error occurs during the evaluation and saving of the model, specifically in the `reset_step` method of the `PartitionedParameterCoordinator` class in DeepSpeed. There's a disagreement in the submodule order between rank 0 and rank 1.
**Possible Causes:**
a. Inconsistent model initialization across processes
b. Data loading discrepancies
c. Non-deterministic operations in the model or data pipeline
d. Issues with DeepSpeed's ZeRO Stage 3 optimization

**Suggestions to resolve the issue:**
a. **Ensure Deterministic Behavior:**
Set a fixed seed for all random number generators (PyTorch, NumPy, Python) at the beginning of your script.
Use `torch.use_deterministic_algorithms(True)` to enforce deterministic operations.

b. **Check Data Loading:**
Ensure that your data loading process is consistent across all ranks.
If using a custom dataset, make sure it's properly sharded or distributed.

c. **Model Initialization:**
Verify that the model is initialized identically across all processes.
If using a pretrained model, ensure it's loaded correctly on all ranks.

d. **DeepSpeed Configuration:**
Review your DeepSpeed configuration, particularly the ZeRO Stage 3 settings.

e. **Gradient Accumulation:**
If using gradient accumulation, ensure it's properly synchronized across processes.

f. **Version Compatibility:**
Check if there are any known issues with the specific versions of DeepSpeed, PyTorch, and other libraries you're using.

g. **Simplified Test:**
Try running a simplified version of your training loop with a smaller model and dataset to isolate the issue.

h. **DeepSpeed Debug Options:**
Enable DeepSpeed's verbose logging to get more information about the state of each rank.

i. **Check for Non-replicated Operations:**
Ensure that any custom operations or data preprocessing steps are replicated identically across all ranks.

**Comment by tjruwase** [comment]
@eonsparks, thanks for suggesting solutions!

**Comment by yiyepiaoling0715** [comment]
> ### **Error Description:**
> The error occurs during the evaluation and saving of the model, specifically in the `reset_step` method of the `PartitionedParameterCoordinator` class in DeepSpeed. There's a disagreement in the submodule order between rank 0 and rank 1. **Possible Causes:** a. Inconsistent model initialization across processes b. Data loading discrepancies c. Non-deterministic operations in the model or data pipeline d. Issues with DeepSpeed's ZeRO Stage 3 optimization
> 
> **Suggestions to resolve the issue:** a. **Ensure Deterministic Behavior:** Set a fixed seed for all random number generators (PyTorch, NumPy, Python) at the beginning of your script. Use `torch.use_deterministic_algorithms(True)` to enforce deterministic operations.
> 
> b. **Check Data Loading:** Ensure that your data loading process is consistent across all ranks. If using a custom dataset, make sure it's properly sharded or distributed.
> 
> c. **Model Initialization:** Verify that the model is initialized identically across all processes. If using a pretrained model, ensure it's loaded correctly on all ranks.
> 
> d. **DeepSpeed Configuration:** Review your DeepSpeed configuration, particularly the ZeRO Stage 3 settings.
> 
> e. **Gradient Accumulation:** If using gradient accumulation, ensure it's properly synchronized across processes.
> 
> f. **Version Compatibility:** Check if there are any known issues with the specific versions of DeepSpeed, PyTorch, and other libraries you're using.
> 
> g. **Simplified Test:** Try running a simplified version of your training loop with a smaller model and dataset to isolate the issue.
> 
> h. **DeepSpeed Debug Options:** Enable DeepSpeed's verbose logging to get more information about the state of each rank.
> 
> i. **Check for Non-replicated Operations:** Ensure that any custom operations or data preprocessing steps are replicated identically across all ranks.

this bug is triggered  when using deepseek-v2-lite (moe) and deepseeed zero3 ,when traing others model(not moe) and depseed zero3,it is ok

**Comment by yiyepiaoling0715** [comment]
> ### **Error Description:**
> The error occurs during the evaluation and saving of the model, specifically in the `reset_step` method of the `PartitionedParameterCoordinator` class in DeepSpeed. There's a disagreement in the submodule order between rank 0 and rank 1. **Possible Causes:** a. Inconsistent model initialization across processes b. Data loading discrepancies c. Non-deterministic operations in the model or data pipeline d. Issues with DeepSpeed's ZeRO Stage 3 optimization
> 
> **Suggestions to resolve the issue:** a. **Ensure Deterministic Behavior:** Set a fixed seed for all random number generators (PyTorch, NumPy, Python) at the beginning of your script. Use `torch.use_deterministic_algorithms(True)` to enforce deterministic operations.
> 
> b. **Check Data Loading:** Ensure that your data loading process is consistent across all ranks. If using a custom dataset, make sure it's properly sharded or distributed.
> 
> c. **Model Initialization:** Verify that the model is initialized identically across all processes. If using a pretrained model, ensure it's loaded correctly on all ranks.
> 
> d. **DeepSpeed Configuration:** Review your DeepSpeed configuration, particularly the ZeRO Stage 3 settings.
> 
> e. **Gradient Accumulation:** If using gradient accumulation, ensure it's properly synchronized across processes.
> 
> f. **Version Compatibility:** Check if there are any known issues with the specific versions of DeepSpeed, PyTorch, and other libraries you're using.
> 
> g. **Simplified Test:** Try running a simplified version of your training loop with a smaller model and dataset to isolate the issue.
> 
> h. **DeepSpeed Debug Options:** Enable DeepSpeed's verbose logging to get more information about the state of each rank.
> 
> i. **Check for Non-replicated Operations:** Ensure that any custom operations or data preprocessing steps are replicated identically across all ranks.

after I  add   "torch.use_deterministic_algorithms(True)" in the train file header, and  add "export CUBLAS_WORKSPACE_CONFIG=:4096:8 "  in ENV, it is still failed like before

**Comment by yiyepiaoling0715** [comment]
> ### **Error Description:**
> The error occurs during the evaluation and saving of the model, specifically in the `reset_step` method of the `PartitionedParameterCoordinator` class in DeepSpeed. There's a disagreement in the submodule order between rank 0 and rank 1. **Possible Causes:** a. Inconsistent model initialization across processes b. Data loading discrepancies c. Non-deterministic operations in the model or data pipeline d. Issues with DeepSpeed's ZeRO Stage 3 optimization
> 
> **Suggestions to resolve the issue:** a. **Ensure Deterministic Behavior:** Set a fixed seed for all random number generators (PyTorch, NumPy, Python) at the beginning of your script. Use `torch.use_deterministic_algorithms(True)` to enforce deterministic operations.
> 
> b. **Check Data Loading:** Ensure that your data loading process is consistent across all ranks. If using a custom dataset, make sure it's properly sharded or distributed.
> 
> c. **Model Initialization:** Verify that the model is initialized identically across all processes. If using a pretrained model, ensure it's loaded correctly on all ranks.
> 
> d. **DeepSpeed Configuration:** Review your DeepSpeed configuration, particularly the ZeRO Stage 3 settings.
> 
> e. **Gradient Accumulation:** If using gradient accumulation, ensure it's properly synchronized across processes.
> 
> f. **Version Compatibility:** Check if there are any known issues with the specific versions of DeepSpeed, PyTorch, and other libraries you're using.
> 
> g. **Simplified Test:** Try running a simplified version of your training loop with a smaller model and dataset to isolate the issue.
> 
> h. **DeepSpeed Debug Options:** Enable DeepSpeed's verbose logging to get more information about the state of each rank.
> 
> i. **Check for Non-replicated Operations:** Ensure that any custom operations or data preprocessing steps are replicated identically across all ranks.

![image](https://github.com/user-attachments/assets/81d31a54-5df5-4281-b8a2-76968692bf35)
![image](https://github.com/user-attachments/assets/e63814be-ca1b-421c-a2f9-59c08ac53036)
interesing point:   rank0 has many  large negative int ,while other rank has many normal int number

**Comment by xuanyaoming** [comment]
> b. **Check Data Loading:** Ensure that your data loading process is consistent across all ranks. If using a custom dataset, make sure it's properly sharded or distributed.

Thanks for the tip. But could you elaborate "properly sharded or distributed" a little further? I encountered the same issue. In my case, everything works fine before I decided to assign different GPU different data. I noticed that the sizes of input data are different between different GPUs. Does that mean "properly sharded" data must have identical shapes on all GPUs?

**Comment by yiyepiaoling0715** [comment]
> > b. **Check Data Loading:** Ensure that your data loading process is consistent across all ranks. If using a custom dataset, make sure it's properly sharded or distributed.
> 
> Thanks for the tip. But could you elaborate "properly sharded or distributed" a little further? I encountered the same issue. In my case, everything works fine before I decided to assign different GPU different data. I noticed that the sizes of input data are different between different GPUs. Does that mean "properly sharded" data must have identical shapes on all GPUs?

have you solved this problem?  can we have a wechat for communication?  my:yiyepiaoling0715

**Comment by xuanyaoming** [comment]
> > > b. **Check Data Loading:** Ensure that your data loading process is consistent across all ranks. If using a custom dataset, make sure it's properly sharded or distributed.
> > 
> > 
> > Thanks for the tip. But could you elaborate "properly sharded or distributed" a little further? I encountered the same issue. In my case, everything works fine before I decided to assign different GPU different data. I noticed that the sizes of input data are different between different GPUs. Does that mean "properly sharded" data must have identical shapes on all GPUs?
> 
> have you solved this problem? can we have a wechat for communication? my:yiyepiaoling0715

Yes. My speculation is correct. Making data in all GPUs have identical shape can solve my problem. I guess some integers discribe the shape of input tensors, and that's why the direct error is "data disagreement". To be honest, I don't know how it works internally, deepspeed is a lot more complex than fairscale

**Comment by yiyepiaoling0715** [comment]
> Making data in all GPUs have identical shape

how to make data in all GPUs have identical shape ?

**Comment by 1737686924** [comment]
I'm having the same problem, how can I fix them，，，![Image](https://github.com/user-attachments/assets/e9f88b5f-d808-410f-be4d-602ece981da6)

**Comment by yiyepiaoling0715** [comment]
> I'm having the same problem, how can I fix them，，，![Image](https://github.com/user-attachments/assets/e9f88b5f-d808-410f-be4d-602ece981da6)

what is your base model?  deepseek-v2 series?

**Comment by QingtaoLi1** [comment]
> > > Making data in all GPUs have identical shape
> > 
> > 
> > how to make data in all GPUs have identical shape ?
> 
> By editing **getitem()** function in your dataset class. For text data, you can truncate the long ones and pad the short ones.

I tried your method, but it's still there. One thing that may need to note: this error happens at the second step instead of the first.

**Comment by zhyang2226** [comment]
I am encountering the same issue. Any solution so far?😭

**Comment by flutist** [comment]
I am encountering the same issue. Any solution so far?😭

**Comment by tjruwase** [comment]
@flutist and @yiyepiaoling0715 can you please try the new leaf module solution for handling MoE models?
https://deepspeed.readthedocs.io/en/latest/training.html#configuring-zero-leaf-modules
